/**
 * Insights Engine — pure prediction & analysis functions.
 *
 * All functions are deterministic and dependency-free (no React, no async).
 * Sources for lift benchmarks:
 *   - Google/Ipsos research on GBP engagement
 *   - BrightLocal Local SEO survey
 *   - Moz Local Search Ranking Factors
 *   - Think With Google mobile speed studies
 */

// ─── Types ─────────────────────────────────────────────────────────────────

export type ImpactTier = "Peak" | "High" | "Medium" | "Low"
export type FactorStatus = "resolved" | "pending"
export type MetricCategory =
  | "direction_requests"
  | "organic_clicks"
  | "rich_results"
  | "ctr"
  | "maps_views"
  | "discovery"

export interface ImpactFactor {
  id: string
  label: string
  lift: number          // fractional multiplier e.g. 0.18 = 18%
  category: MetricCategory
  confidence: number    // 0–100 confidence in the benchmark
  description: string   // one-line explanation
  affectsMetric: string // human-readable metric name
  status: FactorStatus
  estimatedLiftValue: number // extra direction requests this would add
  href: string          // where to fix it
}

export interface TrafficLift {
  baseline: number           // estimated monthly direction requests WITHOUT Presencely
  current: number            // actual current direction requests
  fullPotential: number      // if all actions are completed
  currentLift: number        // already gained from Presencely
  remainingLift: number      // still available if remaining actions done
}

export interface BusyDay {
  day: string
  searches: number
  maps: number
  rawScore: number
  score: number        // 0–100 normalised
  tier: ImpactTier
  recommendation: string
  staffingNote: string
}

export interface ROIResult {
  currentMonthlyVisits: number     // additional visits already generated by Presencely
  fullPotentialVisits: number      // additional visits if fully optimised
  currentRevenue: number           // $ already gained per month
  fullPotentialRevenue: number     // $ available if fully optimised
  pendingActionCount: number
}

// ─── Constants ─────────────────────────────────────────────────────────────

const RAW_FACTORS: Omit<ImpactFactor, "status" | "estimatedLiftValue">[] = [
  {
    id: "reply_reviews",
    label: "Reply to all reviews",
    lift: 0.18,
    category: "direction_requests",
    confidence: 87,
    description: "Businesses that respond to reviews see 18% more direction requests. Google actively promotes active, engaged profiles.",
    affectsMetric: "Direction Requests",
    href: "/dashboard/reputation",
  },
  {
    id: "fix_seo",
    label: "Fix critical SEO issues",
    lift: 0.23,
    category: "organic_clicks",
    confidence: 91,
    description: "Resolving critical on-page SEO issues is the single highest-impact action. Missing meta descriptions alone reduce click-through by up to 15%.",
    affectsMetric: "Organic Clicks",
    href: "/dashboard/seo",
  },
  {
    id: "schema_markup",
    label: "Add Restaurant schema markup",
    lift: 0.12,
    category: "rich_results",
    confidence: 82,
    description: "Structured data enables rich results (star ratings, menu, hours) directly in Google search, increasing impressions by up to 12%.",
    affectsMetric: "Search Impressions",
    href: "/dashboard/seo",
  },
  {
    id: "page_speed",
    label: "Improve page speed to <2s",
    lift: 0.09,
    category: "ctr",
    confidence: 78,
    description: "A 1-second improvement in page load time increases conversions by 7%. Your site currently loads in 4.2s — well above the 2s target.",
    affectsMetric: "Website Conversions",
    href: "/dashboard/seo",
  },
  {
    id: "gbp_posts",
    label: "Post weekly on Google Business Profile",
    lift: 0.15,
    category: "maps_views",
    confidence: 84,
    description: "Businesses posting ≥4x/month on GBP receive 3x more Google Maps impressions and 15% more direction requests than inactive profiles.",
    affectsMetric: "Google Maps Views",
    href: "/dashboard/visibility",
  },
  {
    id: "complete_gbp",
    label: "Complete GBP menu & photos",
    lift: 0.14,
    category: "discovery",
    confidence: 79,
    description: "Profiles with 100+ photos and a complete menu get 520% more calls and 1,065% more website clicks than sparse profiles (Google data).",
    affectsMetric: "Discovery Searches",
    href: "/dashboard/visibility",
  },
]

const TIER_RECOMMENDATIONS: Record<ImpactTier, { recommendation: string; staffingNote: string }> = {
  Peak:   { recommendation: "Max staff on. Consider reservations-only or pre-order policy to handle demand.", staffingNote: "Staff at 100% capacity" },
  High:   { recommendation: "Strong day. Run limited-time offers or upsells to boost average spend per visit.", staffingNote: "Staff at 80% capacity" },
  Medium: { recommendation: "Opportunity day. A Google Posts deal or social promotion can drive extra walk-ins.", staffingNote: "Standard staffing" },
  Low:    { recommendation: "Quiet day. Best for staff training, deep prep, or a loyalty-member-only special.", staffingNote: "Reduced staffing" },
}

// ─── Algorithm functions ────────────────────────────────────────────────────

/**
 * Determines which factors are resolved vs pending, and estimates
 * the additional direction requests each factor could add.
 */
export function computeImpactBreakdown(
  seoIssues: Array<{ id: number; severity: string; title: string }>,
  recentReviews: Array<{ replied: boolean }>,
  currentDirections: number
): ImpactFactor[] {
  const unrepliedCount = recentReviews.filter((r) => !r.replied).length
  const hasCriticalSeo = seoIssues.some((i) => i.severity === "critical")
  const hasSchemaIssue = seoIssues.some((i) => i.title.toLowerCase().includes("schema"))
  const hasSpeedIssue = seoIssues.some((i) => i.title.toLowerCase().includes("load"))

  const statusMap: Record<string, FactorStatus> = {
    reply_reviews: unrepliedCount > 0 ? "pending" : "resolved",
    fix_seo:       hasCriticalSeo     ? "pending" : "resolved",
    schema_markup: hasSchemaIssue     ? "pending" : "resolved",
    page_speed:    hasSpeedIssue      ? "pending" : "resolved",
    gbp_posts:     "pending", // No GBP posting data available — treat as opportunity
    complete_gbp:  "pending", // No GBP completeness score — treat as opportunity
  }

  return RAW_FACTORS.map((factor) => {
    const status = statusMap[factor.id]
    const estimatedLiftValue = Math.round(currentDirections * factor.lift)
    return { ...factor, status, estimatedLiftValue }
  })
}

/**
 * Computes traffic lift figures comparing Presencely vs no software.
 *
 * Model:
 *  - "baseline" uses the MEASURED visibility gap (from the projection chart) to
 *    back-calculate where the business would be without the software. This anchors
 *    the ROI to real observed data rather than resolved-action assumptions.
 *  - "fullPotential" = current × (1 + pendingLift) if all remaining actions done.
 *
 * @param visibilityGapPercent - measured % gap between withPresencely and withoutPresencely
 *   at the latest historical data point (e.g. 36 means 36% higher with the software).
 */
export function computeTrafficLift(
  currentDirections: number,
  factors: ImpactFactor[],
  visibilityGapPercent: number
): TrafficLift {
  // Use measured gap to determine baseline
  const baseline = Math.round(currentDirections / (1 + visibilityGapPercent / 100))
  const currentLift = currentDirections - baseline

  // Full potential = current × (1 + sum of pending factor lifts)
  const pendingLift = factors
    .filter((f) => f.status === "pending")
    .reduce((sum, f) => sum + f.lift, 0)

  const fullPotential = Math.round(currentDirections * (1 + pendingLift))
  const remainingLift = fullPotential - currentDirections

  return { baseline, current: currentDirections, fullPotential, currentLift, remainingLift }
}

/**
 * Converts direction-request lift to estimated visits and revenue.
 */
export function computeROI(
  trafficLift: TrafficLift,
  avgSpend: number,
  conversionRate: number,
  pendingFactors: ImpactFactor[]
): ROIResult {
  const currentMonthlyVisits     = Math.round(trafficLift.currentLift   * conversionRate)
  const fullPotentialVisits      = Math.round((trafficLift.currentLift + trafficLift.remainingLift) * conversionRate)
  const currentRevenue           = Math.round(currentMonthlyVisits  * avgSpend)
  const fullPotentialRevenue     = Math.round(fullPotentialVisits    * avgSpend)
  const pendingActionCount       = pendingFactors.filter((f) => f.status === "pending").length

  return { currentMonthlyVisits, fullPotentialVisits, currentRevenue, fullPotentialRevenue, pendingActionCount }
}

/**
 * Scores each day of the week for predicted foot-traffic busyness.
 * Score = (searches × 0.4) + (maps × 0.6), normalised 0–100.
 * Maps clicks weighted higher — they signal stronger intent to visit.
 */
export function computeBusiestDays(
  weeklySearchData: Array<{ day: string; searches: number; maps: number }>
): BusyDay[] {
  const withScores = weeklySearchData.map((d) => ({
    ...d,
    rawScore: d.searches * 0.4 + d.maps * 0.6,
  }))

  const maxScore = Math.max(...withScores.map((d) => d.rawScore))

  return withScores.map((d) => {
    const score = Math.round((d.rawScore / maxScore) * 100)
    const tier: ImpactTier =
      score >= 85 ? "Peak" :
      score >= 65 ? "High" :
      score >= 40 ? "Medium" : "Low"

    return {
      ...d,
      score,
      tier,
      ...TIER_RECOMMENDATIONS[tier],
    }
  })
}

/**
 * Overall confidence in the predictions — weighted average of
 * pending factor confidence scores.
 */
export function computeOverallConfidence(factors: ImpactFactor[]): number {
  const pending = factors.filter((f) => f.status === "pending")
  if (pending.length === 0) return 95
  const avg = pending.reduce((sum, f) => sum + f.confidence, 0) / pending.length
  return Math.round(avg)
}

/**
 * Percentage gap between Presencely trajectory and the no-software baseline
 * at the latest historical data point.
 */
export function computeVisibilityGapPercent(
  projectionData: Array<{ withPresencely: number; withoutPresencely: number; projected: boolean }>
): number {
  const lastHistorical = [...projectionData].reverse().find((d) => !d.projected)
  if (!lastHistorical) return 0
  return Math.round(
    ((lastHistorical.withPresencely - lastHistorical.withoutPresencely) /
      lastHistorical.withoutPresencely) * 100
  )
}

// ─── Customer Intelligence Types ─────────────────────────────────────────────

export interface FunnelStage {
  label: string
  value: number
  iconName: string
  conversionToNext: number | null   // % that proceed to next stage
  industryAvg: number | null        // industry benchmark for this conversion
  aboveAvg: boolean | null          // true if we're beating industry
  formatted: string
}

export interface LoyaltyStats {
  avgDistance: number
  loyaltyRadius80pct: number
  walkInRate: number
  destinationRate: number
  estimatedTrueMonthlyVisitors: number
}

// ─── Customer Intelligence Functions ─────────────────────────────────────────

/**
 * Computes the full discovery funnel from Google searches through to revenue.
 * Each stage shows the conversion rate to the next and vs industry average.
 */
export function computeDiscoveryFunnel(
  searchImpressions: number,
  mapsViews: number,
  directionRequests: number,
  conversionRate: number,
  avgSpend: number
): FunnelStage[] {
  const estimatedVisits = Math.round(directionRequests * conversionRate)
  const revenue = estimatedVisits * avgSpend
  const searchToMaps = Math.round((mapsViews / searchImpressions) * 100)
  const mapsToDirection = Math.round((directionRequests / mapsViews) * 100)
  const directionToVisit = Math.round(conversionRate * 100)

  return [
    {
      label: "Google Searches",
      value: searchImpressions,
      iconName: "Search",
      conversionToNext: searchToMaps,
      industryAvg: 28,
      aboveAvg: searchToMaps > 28,
      formatted: searchImpressions.toLocaleString(),
    },
    {
      label: "Maps Profile Views",
      value: mapsViews,
      iconName: "MapPin",
      conversionToNext: mapsToDirection,
      industryAvg: 15,
      aboveAvg: mapsToDirection > 15,
      formatted: mapsViews.toLocaleString(),
    },
    {
      label: "Direction Requests",
      value: directionRequests,
      iconName: "Navigation",
      conversionToNext: directionToVisit,
      industryAvg: 55,
      aboveAvg: directionToVisit > 55,
      formatted: directionRequests.toLocaleString(),
    },
    {
      label: "Estimated Visits",
      value: estimatedVisits,
      iconName: "Users",
      conversionToNext: null,
      industryAvg: null,
      aboveAvg: null,
      formatted: estimatedVisits.toLocaleString(),
    },
    {
      label: "Monthly Revenue",
      value: revenue,
      iconName: "DollarSign",
      conversionToNext: null,
      industryAvg: null,
      aboveAvg: null,
      formatted: `CHF ${revenue.toLocaleString()}`,
    },
  ]
}

/**
 * Computes loyalty radius and customer distance statistics.
 * Walk-in locals (<0.5 mi) rarely use Google directions — their true count
 * is estimated by scaling up the direction-request-based visitor count.
 */
export function computeLoyaltyRadius(
  distanceData: Array<{ range: string; pct: number }>,
  directionBasedVisitors: number
): LoyaltyStats {
  const walkInRate = distanceData.find((d) => d.range === "<0.5 km")?.pct ?? 38
  const destinationRate = distanceData
    .filter((d) => d.range === "5–10 km" || d.range === "10+ km")
    .reduce((sum, d) => sum + d.pct, 0)

  const midpoints: Record<string, number> = {
    "<0.5 km":  0.25,
    "0.5–2 km": 1.2,
    "2–5 km":   3.5,
    "5–10 km":  7.5,
    "10+ km":   15.0,
  }

  const avgDistanceMiles = distanceData.reduce((sum, d) => {
    return sum + (midpoints[d.range] ?? 5) * (d.pct / 100)
  }, 0)

  // 80th percentile loyalty radius
  let cumulative = 0
  let loyaltyRadius80pct = 5
  for (const d of distanceData) {
    cumulative += d.pct
    if (cumulative >= 80) {
      loyaltyRadius80pct = midpoints[d.range] ?? 5
      break
    }
  }

  // Walk-in locals rarely request directions, so direction-based count
  // only captures (100 - walkInRate)% of true visitors
  const estimatedTrueMonthlyVisitors = Math.round(
    directionBasedVisitors / ((100 - walkInRate) / 100)
  )

  return {
    avgDistance: Math.round(avgDistanceMiles * 10) / 10,
    loyaltyRadius80pct,
    walkInRate,
    destinationRate,
    estimatedTrueMonthlyVisitors,
  }
}

// ─── Staffing Intelligence Types ─────────────────────────────────────────────

export interface StaffingROI {
  laborCost: number
  revenue: number
  laborPct: number
  grossMargin: number
  overstaffCostPerExtraStaff: number   // daily cost of 1 unnecessary extra staff
  understaffRevenueLoss: number        // estimated 15% revenue loss if 1 staff short at peak
}

// ─── Staffing Intelligence Functions ─────────────────────────────────────────

/**
 * Computes minimum staff needed for a shift.
 * Uses ceil(visitors / (hours × capacityPerStaff)) with a minimum of 1.
 */
export function computeStaffNeeded(
  visitorsInShift: number,
  shiftHours: number,
  capacityPerStaffPerHour: number
): number {
  return Math.max(1, Math.ceil(visitorsInShift / (shiftHours * capacityPerStaffPerHour)))
}

/**
 * Computes total labour cost for a given number of staff-hours.
 */
export function computeLaborCost(staffHours: number, hourlyWage: number): number {
  return staffHours * hourlyWage
}

/**
 * Computes staffing ROI breakdown:
 *  - grossMargin after labour
 *  - daily cost of overstaffing by 1
 *  - revenue loss from understaffing by 1 at peak
 */
export function computeStaffingROI(
  revenue: number,
  laborCost: number,
  hourlyWage: number,
  openHours: number
): StaffingROI {
  return {
    laborCost,
    revenue,
    laborPct: Math.round((laborCost / revenue) * 100),
    grossMargin: revenue - laborCost,
    overstaffCostPerExtraStaff: Math.round(hourlyWage * openHours),
    understaffRevenueLoss: Math.round(revenue * 0.15),
  }
}
